### ISSUE TITLE
Add Spelsberg Wallbox SmartPro

### ISSUE THREAD

**Issue by mfuchs1984** [enbility/devices#1]
I own a Spelsberg Wallbox SmartPro with EEBUS support and use it with EEBUS in an experimental EEVC environment. I can add the device to the repository.

**Comment by DerAndereAndi** [comment]
Hi @mfuchs1984 

that would be great! You could either create a PR if you are able to fetch the corresponding EEBUS responses from the evcc TRACE output. Or you could provide a log file and I'll do it.

Let me know if you need help!

**Comment by mfuchs1984** [comment]
Opened a pull request. 

After further research, the wallbox seems to be Bender controller based. I am currently successfully using it with the Bender integration in EVCC since I was not able to really control charging through EEBUS. If you want me to perform some more testing with EEBUS let me know. Spelsberg promises a software update for phase switching during this year, have you heard anything about Bender controllers supporting this in the future? Is this generally part of the EEBUS standard?

**Comment by DerAndereAndi** [comment]
Phase switching is not possible in EEBUS today, it is not supported.

Thanks for the PR!

As you got the data, it should also work with the EEBUS integration. If you want to try it out, please open a discussion in the evcc repository and provide more details on what your problem exactly is.
